services:
  web:
    image: appcircle-api:latest
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    networks:
      - appcircle-network
  
  db:
    image: postgres:15
    container_name: appcircle-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: appcircle
      POSTGRES_USER: appcircle
      POSTGRES_PASSWORD: P!x3l2214
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appcircle-network

  phppgadmin:
    image: dockage/phppgadmin:latest
    ports:
      - "8080:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_USERNAME=appcircle
      - PHP_PG_ADMIN_SERVER_PASSWORD=P!x3l2214
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=appcircle
      - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
      - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall
      - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
    depends_on:
      - db
    networks:
      - appcircle-network

volumes:
  dbdata:

networks:
  appcircle-network:
    driver: bridge