services:
  web:
    container_name: appcircle-web
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    networks:
      - appcircle-network
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: postgres:15
    container_name: appcircle-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - appcircle-network

  phppgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - .env
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - appcircle-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve && run llama3
    networks:
      - appcircle-network

volumes:
  dbdata:
  ollama_data:

networks:
  appcircle-network:
    driver: bridge